#!/bin/bash
#
# JobHunter Startup Script for Linux
#

if [ "${JAVA_HOME}" == "" ]; then
    echo "JAVA_HOME Not set. Install the JRE and set the JAVA_HOME in your initialization file"
    exit 1
fi

if [ ! -d "${JAVA_HOME}" ] ; then
    echo "Java ${JAVA_HOME} Directory doesn't exist."
    exit 1
else
    if [ ! -x "${JAVA_HOME}/bin/java" ] ; then
        echo "Java binary error: not found or not executable"
        exit 1
    fi
fi

do_start () {
    local path="lib/*:etc"
    local opts=""

    local exit_code=10
    while [ $exit_code -eq 10 ]; do
        "${JAVA_HOME}/bin/java" ${opts} -cp "${path}" jobhunter.gui.MainApp
        exit_code=$?
    done
}

do_debug () {
    local opts="-Ddebug=true"
    local path="lib/*:etc"
    "${JAVA_HOME}/bin/java" ${opts} -cp "${path}" jobhunter.gui.MainApp
}

case ${1} in
    start)
        do_start
    ;;

    debug)
        do_demo
    ;;

    *)
        do_start
    ;;
esac

exit 0