#!/bin/bash
#
# JobHunter Startup Script for Linux
#

# We need to come to our location
cd ${0%/*}

if [ "${JAVA_HOME}" == "" ]; then
    echo "JAVA_HOME Not set. Install the JRE and set the JAVA_HOME in your initialization file"
    sleep 5
    exit 1
fi

if [ ! -d "${JAVA_HOME}" ] ; then
    echo "Java ${JAVA_HOME} Directory doesn't exist."
    exit 1
else
    if [ ! -x "${JAVA_HOME}/bin/java" ] ; then
        echo "Java binary error: not found or not executable"
        exit 1
    fi
fi

do_start () {
    local path="lib/*"
    local opts=""

    local exit_code=10
    while [ $exit_code -eq 10 ]; do
        "${JAVA_HOME}/bin/java" ${opts} -cp "${path}" jobhunter.gui.MainApp > /dev/null 2>&1
        exit_code=$?
    done
}

do_debug () {
    local opts="-Ddebug=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044"
    local path="lib/*"
    "${JAVA_HOME}/bin/java" ${opts} -cp "${path}" jobhunter.gui.MainApp
}

case ${1} in
    start)
        do_start
    ;;

    debug)
        do_debug
    ;;

    *)
        do_start
    ;;
esac

exit 0